import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/header";
import Nav from "./components/nav";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "H. M. Illustration",
  description: "Generated by create next app",
  keywords:
    "illustration, sequential art, graphic art, graphic design, comic art,",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
